### ISSUE TITLE
Display seats

### ISSUE THREAD

**Issue by aviau** [lanets/floorplanets#1]
As a first feature, I'd like to be able to display seats.

This is 100% HTML + Javascript, no back-end involved.

I remember @ppot wanted to use http://paperjs.org, so that might help.

**Comment by zergov** [comment]
First of all, I looked at seats.io floorplan builder to get some inspiration. It's easy to use and i managed to quikcly draft out the layout of a stage / theater.
The label assignments on seats also works great. I feel like a basic `builder` module like this is a MUST to include in this project somewhere during the developement AKA future project.

I will start by writing a JS interface that wraps paper.js and allow us to create the basic items used to model a floorplan. I propose to first implement two shapes: `seat (circle)` and `table (rectangle)`.

Future module will use this JS interface as building blocks for more complex functionnality I.E the floorplan builder.

**Comment by zergov** [comment]
I started working on this issue on branch : https://github.com/lanets/floorplan-2/tree/f_display_seats

**Comment by zergov** [comment]
#13 is answering this Issue.

It displays some seats based off of a payload containing informations about the position of some seats.

**Comment by zergov** [comment]
Closing this issue as the current master branch is way ahead of this issue.
